/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalhodesktop;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class AcessoFrame extends javax.swing.JFrame {
    private DefaultTableModel modelo = new DefaultTableModel();
    private int linhaSelecionada = -1;
    /**
     * Creates new form AcessoFrame
     */
    public AcessoFrame() {
        initComponents();
        setLocationRelativeTo(this);
        carregaTabela();
        carregaTabelaServico();
    }
    
    public void carregaTabela() {

        modelo.addColumn("PEÇA");
        modelo.addColumn("QUANTIDADE");
        modelo.addColumn("VALOR UNITARIO");
        tbServico.setModel(modelo);

        tbServico.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbServico.getColumnModel().getColumn(1).setPreferredWidth(120);
        tbServico.getColumnModel().getColumn(2).setPreferredWidth(230);

    }
    
    public void carregaTabelaServico() {

        modelo.addColumn("SERVICO");
        modelo.addColumn("VALOR");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfDataNasc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfModelo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfMarca = new javax.swing.JTextField();
        tfAno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfPlaca = new javax.swing.JTextField();
        tfCor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tfDesc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfPeca = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfQuant = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfValorUn = new javax.swing.JTextField();
        btAdicionar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbServico = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        tfServico = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfValorServico = new javax.swing.JTextField();
        btAdicionarServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Telefone:");

        jLabel3.setText("Endereço:");

        jLabel4.setText("CPF:");

        jLabel5.setText("Data Nasc:");

        jLabel6.setText("Modelo:");

        jLabel7.setText("Marca:");

        jLabel8.setText("Ano:");

        jLabel9.setText("Placa:");

        jLabel10.setText("Cor:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Dados Cliente");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Ordem de Serviço");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jLabel13.setText("Descrição do Problema:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Peças/Serviço");

        jLabel15.setText("Peça:");

        jLabel16.setText("Quant:");

        jLabel17.setText("Valor Un:");

        btAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btAdicionar.setText("+");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Dados Carro");

        tbServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Peças:", "Quantidade:", "Valor Unitario:"
            }
        ));
        jScrollPane3.setViewportView(tbServico);

        jLabel19.setText("Serviço:");

        jLabel21.setText("Valor Serviço");

        btAdicionarServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btAdicionarServico.setText("+");
        btAdicionarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDesc)
                    .addComponent(jScrollPane3))
                .addGap(306, 306, 306))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(tfServico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btAdicionarServico))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(tfPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(tfQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfValorUn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(223, 223, 223))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(42, 42, 42)
                                        .addComponent(tfCpf))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNome)
                                            .addComponent(tfTelefone)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfDataNasc))
                                    .addComponent(tfEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAdicionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel11)
                                .addGap(240, 240, 240))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfModelo)
                                    .addComponent(tfMarca)
                                    .addComponent(tfAno)
                                    .addComponent(tfPlaca)
                                    .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)))
                .addContainerGap(369, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(tfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(tfCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tfQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tfValorUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdicionar))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(tfValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(btAdicionarServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(tfDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel20))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double valorTotal;
    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
     
       
        String peca = tfPeca.getText();
        String quant = tfQuant.getText();
        String valorUn = tfValorUn.getText();
        
        
        if (peca.isEmpty() || peca.equals("") || quant.isEmpty() || quant.equals("") || valorUn.isEmpty() || valorUn.equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!quant.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "O campo QUANTIDADE deve conter apenas números!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!valorUn.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "O campo VALOR UNITARIO deve conter apenas números!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!peca.matches("[a-zA-Z]+")){
           JOptionPane.showMessageDialog(null, "O campo PEÇA deve apenas conter letras!", "Atenção!", JOptionPane.ERROR_MESSAGE);
           return;
       }
        
        else{
            if (linhaSelecionada >= 0) {
            modelo.removeRow(linhaSelecionada);
            modelo.insertRow(linhaSelecionada, new Object[]{peca, quant, valorUn});
        } else {
            modelo.addRow(new Object[]{peca, quant, valorUn});
            JOptionPane.showMessageDialog(this, "SUCESSO!");
        }

        tfPeca.setText("");
        tfQuant.setText("");
        tfValorUn.setText("");
        tfPeca.requestFocus();
        linhaSelecionada = -1;
        
        double valor = Double.parseDouble(valorUn);
        int quantidade = Integer.parseInt(quant);
        
        valorTotal = valor * quantidade;
        
        
        
        Pecas pecas = new Pecas();
        pecas.setPeca(peca);
        pecas.setQuantidade(quantidade);
        pecas.setValorUn(valor);
        
        
        Controller.getInstance().salvarPecas(pecas);
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        
        String nome = tfNome.getText();
        String telefone = tfTelefone.getText();
        String endereco = tfEndereco.getText();
        String cpf = tfCpf.getText();
        String dataNasc = tfDataNasc.getText();
        
        String modelo = tfModelo.getText();
        String marca = tfMarca.getText();
        String ano = tfAno.getText();
        String placa = tfPlaca.getText();
        String cor = tfCor.getText();
        
        String descricao = tfDesc.getText();
        
        if (nome.isEmpty() || nome.equals("") || telefone.isEmpty() || telefone.equals("") || endereco.isEmpty() || endereco.equals("") ||
            cpf.isEmpty() || cpf.equals("") || dataNasc.isEmpty() || dataNasc.equals("") ||
            modelo.isEmpty() || modelo.equals("") || marca.isEmpty() || marca.equals("") || ano.isEmpty() || ano.equals("") ||
            placa.isEmpty() || placa.equals("") || cor.isEmpty() || cor.equals("") || descricao.isEmpty() || descricao.equals("")) {
            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatorios!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!nome.matches("[a-zA-Z]+")){
           JOptionPane.showMessageDialog(null, "O campo NOME deve apenas conter letras!", "Atenção!", JOptionPane.ERROR_MESSAGE);
           tfNome.setText("");
           tfNome.requestFocus();
           return;
       }
        if (!telefone.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "O campo TELEFONE deve conter apenas números!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            tfTelefone.setText("");
            tfTelefone.requestFocus();
            return;
        }
        
        if (!endereco.matches("[a-zA-Z]+")){
           JOptionPane.showMessageDialog(null, "O campo ENDERECO deve apenas conter letras!", "Atenção!", JOptionPane.ERROR_MESSAGE);
           tfEndereco.setText("");
           tfEndereco.requestFocus();
           return;
       }
        if (!cpf.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "O campo CPF deve conter apenas números mo formato de (999.999.999-99)!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            tfCpf.setText("");
            tfCpf.requestFocus();
            return;
        }
        if (!dataNasc.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "O campo DATA DE NASCIMENTO deve conter apenas números no formato de (99/99/9999)!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            tfDataNasc.setText("");
            tfDataNasc.requestFocus();
            return;
        }
        
        if (!modelo.matches("[a-zA-Z]+")){
           JOptionPane.showMessageDialog(null, "O campo MODELO deve apenas conter letras!", "Atenção!", JOptionPane.ERROR_MESSAGE);
           tfModelo.setText("");
           tfModelo.requestFocus();
           return;
       }
        
         if (!marca.matches("[a-zA-Z]+")){
           JOptionPane.showMessageDialog(null, "O campo MARCA deve apenas conter letras!", "Atenção!", JOptionPane.ERROR_MESSAGE);
           tfMarca.setText("");
           tfMarca.requestFocus();
           return;
       }
        if (!ano.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "O campo ANO deve conter apenas números!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            tfAno.setText("");
            tfAno.requestFocus();
            return;
        }
        
        
        
        
        
       
        if (!cor.matches("[a-zA-Z]+")){
           JOptionPane.showMessageDialog(null, "O campo COR deve apenas conter letras!", "Atenção!", JOptionPane.ERROR_MESSAGE);
           tfCor.setText("");
           tfCor.requestFocus();
           return;
       }
        
        else{            
            double valorFinal;
            valorFinal = valorTotalServico + valorTotal;
            Relatorio relatorio = new Relatorio();
            relatorio.setValorTotal(valorFinal);
            relatorio.setDescricao(descricao);
            
            Controller.getInstance().salvarRelatorio(relatorio);
            
            Cliente cliente = new Cliente();
            cliente.setNome(nome);
            cliente.setTelefone(telefone);
            cliente.setEndereco(endereco);
            cliente.setCpf(cpf);
            cliente.setDataNasc(dataNasc);
        
            Controller.getInstance().salvarCliente(cliente);
            
            Carro carro = new Carro();
            carro.setModelo(modelo);
            carro.setMarca(marca);
            carro.setAno(ano);
            carro.setPlaca(placa);
            carro.setCor(cor);
        
            Controller.getInstance().salvarCarro(carro);

            Controller.getInstance().salvarRelatorio(relatorio);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRelatorio().setVisible(true);
            }
        });
        }        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTrabalhoDesktop().setVisible(true);
            }
        });
    }//GEN-LAST:event_btVoltarActionPerformed
    double valorTotalServico;
    private void btAdicionarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarServicoActionPerformed
        String servico = tfServico.getText();
        String valor = tfValorServico.getText();
        
        if (servico.isEmpty() || servico.equals("") || valor.isEmpty() || valor.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!valor.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "O campo VALOR SERVIÇO deve conter apenas números!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
         if (!servico.matches("[a-zA-Z]+")){
           JOptionPane.showMessageDialog(null, "O campo SERVIÇO deve apenas conter letras!", "Atenção!", JOptionPane.ERROR_MESSAGE);
           return;
       }
        
        else{
            if (linhaSelecionada >= 0) {
            modelo.removeRow(linhaSelecionada);
            modelo.insertRow(linhaSelecionada, new Object[]{servico, valor});
        } else {
            modelo.addRow(new Object[]{servico, valor});
            JOptionPane.showMessageDialog(this, "SUCESSO!");
        }
            tfServico.setText("");
            tfValorServico.setText("");
            tfServico.requestFocus();
            linhaSelecionada = -1;
            
            double valorServico = Double.parseDouble(valor);
            valorTotalServico+= valorServico;
            
            Servico servicoo = new Servico();
            servicoo.setServico(servico);
            servicoo.setValor(valorServico);
            
            Controller.getInstance().salvarServico(servicoo);
        }
    }//GEN-LAST:event_btAdicionarServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAdicionarServico;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbServico;
    private javax.swing.JTextField tfAno;
    private javax.swing.JTextField tfCor;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfDataNasc;
    private javax.swing.JTextField tfDesc;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPeca;
    private javax.swing.JTextField tfPlaca;
    private javax.swing.JTextField tfQuant;
    private javax.swing.JTextField tfServico;
    private javax.swing.JTextField tfTelefone;
    private javax.swing.JTextField tfValorServico;
    private javax.swing.JTextField tfValorUn;
    // End of variables declaration//GEN-END:variables
}
